### ISSUE TITLE
Debug CSV Logger to USB

### ISSUE THREAD

**Issue by aswerdlow935** [themilkenknights/MilkenKnights-PowerUp#8]
CSV logging only working for Superstructure

**Comment by alexanderswerdlow** [comment]
Causes code cycle slowdown...need to find a solution that doesn't slow down code

**Comment by AustinShalit** [comment]
Maybe do this in a thread with a thread safe queue of lines to write to the file?

**Comment by alexanderswerdlow** [comment]
I currently changed to write every 20ms vs 5ms which seemed to fix things. The ReflectingCSVWriter is added to every 20ms but I just changed it so that it waits to write until the code is stopped. I’m not sure whether this will add to the memory issues but will test today. If so, I’ll look into a thread safe queue.

**Comment by alexanderswerdlow** [comment]
Fixed, All debug classes must have all variables as public

**Comment by AustinShalit** [comment]
Umm... that is a weird fix.  Is your debugging using reflection?

**Comment by alexanderswerdlow** [comment]
Yes, I believe so...I didnt writ the class but I’m using a ‘ReflectingCSVWriter’ that uses java.lang.reflect.Field

**Comment by AustinShalit** [comment]
Yea.  The way that is written right now it will only grab the public fields.

If you wanted it to grab all fields, you could set the access flag on the fields using this: https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AccessibleObject.html#setAccessible-boolean-
